### PR TITLE
Added an instance of random data to the repo

### PR DESCRIPTION
**Pull request by BGluth**
- For whatever reason I only had a csv for blob data and not random data.

### CODE REVIEW

**Comment by dzeber** [comment]
@BGluth Could you also include the updated version of the data generation notebook with the code to write this file in the PR?

I merged #14, so you can pull and rebase this branch on top of that.

**Comment by BGluth** [comment]
Ok @dzeber should be good to go. Let me know if you want me to squash.

**Comment by crankycoder** [comment]
@dzeber @BGluth is this PR still useful?

**Comment by BGluth** [comment]
@crankycoder Sorry... I'm sometimes not seeing these notifications in my email.

As far as I know we can still use the truly random dataset, so I think this should still be merged.

**Pull request merged**
