### PR TITLE
Update simulation_util.py

### PR DESCRIPTION
**Pull request by Shivansh2407**
Should client_num be m? #17

### CODE REVIEW

**Comment by Shivansh2407** [comment]
Please check and merge this PR

**Comment by crankycoder** [comment]
@maharshmellow @BGluth @zhaoyuxuan can one of you double check that using `m like this is correct?

**Review by maharshmellow — APPROVED** [review]
Good catch 😄 This looks good!

**Review by zhaoyuxuan — APPROVED** [review]

**Comment by Shivansh2407** [comment]
Cool Thanks : )

**Pull request merged**
