### PR TITLE
Features/pypi packaging

### PR DESCRIPTION
**Pull request by crankycoder**
This PR covers #21 among other things.

This merges in everything from https://github.com/mozilla/CANOSP-2019/pull/18

I've shuffled files around a little to enable packagaing up code into a PyPI library and setup a preliminary Docker container to run everything.

Tests are available under the tests directory and can be run using `python setup.py pytest`, or by using the Makefile to run tests inside the docker container.

### CODE REVIEW

**Comment by crankycoder** [comment]
@maharshmellow @BGluth @zhaoyuxuan I've tried to keep the import changes in the notebooks to be minimal.  Hopefully this should be pretty clear.  If not - give me a shout.

**Comment by BGluth** [comment]
Seems to run fine on my machine.

So, just as a sanity check:
- The tests cases that we write would apply to all simulations right?
- I'm a bit confused as to how the URI interface is used (ie. `"/api/v1/client_update/<string:client_id>"`). I know this is going to be the plumbing to easily run tests, but I don't really understand how this works. Is this something that I need to worry about?
- Would `ingest_client_data` be passed in JSON that contains *all* the data for a client in the entire dataset or just one piece of data at a time?
- The idea is to move most of the code from `sim_util.py` over to here right?

**Review by BGluth — APPROVED** [review]

**Comment by crankycoder** [comment]
@BGluth yes - let's get test cases wrapped around all the simulations so that we can verify behavior on an automated basis.

@maharshmellow @zhaoyuxuan can you guys give this a try on your machine and then merge so that we don't get divergent codebases?  You can [checkout a pull request locally](https://help.github.com/en/articles/checking-out-pull-requests-locally).

Let's take the rest of this discussion to slack.

**Review by zhaoyuxuan — APPROVED** [review]
Works on my local machine!!!

**Review by maharshmellow — APPROVED** [review]
Everything works on mine too 😃

**Pull request merged**
